version: 2.1


# Executors define environment where jobs will be run.
executors:
    py2:
        docker:
            - image: pyne/ubuntu_18.04_py2_pyne-deps
        environment:
            PYTHONPATH: /root/project/
    py3:
        docker:
            - image: pyne/ubuntu_18.04_py3_pyne-deps
        environment:
            PYTHONPATH: /root/project/
    py2_s:
        docker:
            - image: pyne/ubuntu_18.04_py2_pyne-deps
        environment:
            PYTHONPATH: /root/project/source
    py3_s:
        docker:
            - image: pyne/ubuntu_18.04_py3_pyne-deps
        environment:
            PYTHONPATH: /root/project/source
            
jobs:
    pytest_noinit_python2_direct:
        executor:
            name: py2
        steps:
            - checkout
            - run: apt update; apt -y install curl python-yaml
            - run: curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py; python get-pip.py
            - run: echo $PYTHONPATH
            - run: pip install -U pytest
            - run: rm -rf source/__init__.py
            - run: pytest tests/test_direct_import.py -vvv 
    pytest_noinit_python2_s_direct:
        executor:
            name: py2_s
        steps:
            - checkout
            - run: apt update; apt -y install curl python-yaml
            - run: curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py; python get-pip.py
            - run: echo $PYTHONPATH
            - run: pip install -U pytest
            - run: rm -rf source/__init__.py
            - run: pytest tests/test_direct_import.py -vvv 
    pytest_noinit_python3_direct:
        executor:
            name: py3
        steps:
            - checkout
            - run: apt update; apt -y install curl python3-yaml
            - run: curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py; python get-pip.py
            - run: echo $PYTHONPATH
            - run: pip install -U pytest
            - run: rm -rf source/__init__.py
            - run: pytest tests/test_direct_import.py -vvv 
    pytest_noinit_python3_s_direct:
        executor:
            name: py3_s
        steps:
            - checkout
            - run: apt update; apt -y install curl python3-yaml
            - run: curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py; python get-pip.py
            - run: echo $PYTHONPATH
            - run: pip install -U pytest
            - run: rm -rf source/__init__.py
            - run: pytest tests/test_direct_import.py -vvv 
    
    pytest_noinit_python2_from:
        executor:
            name: py2
        steps:
            - checkout
            - run: apt update; apt -y install curl python-yaml
            - run: curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py; python get-pip.py
            - run: echo $PYTHONPATH
            - run: pip install -U pytest
            - run: rm -rf source/__init__.py
            - run: pytest tests/test_from_source.py -vvv 
    pytest_noinit_python2_s_from:
        executor:
            name: py2_s
        steps:
            - checkout
            - run: apt update; apt -y install curl python-yaml
            - run: curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py; python get-pip.py
            - run: echo $PYTHONPATH
            - run: pip install -U pytest
            - run: rm -rf source/__init__.py
            - run: pytest tests/test_from_source.py -vvv 
    pytest_noinit_python3_from:
        executor:
            name: py3
        steps:
            - checkout
            - run: apt update; apt -y install curl python3-yaml
            - run: curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py; python get-pip.py
            - run: echo $PYTHONPATH
            - run: pip install -U pytest
            - run: rm -rf source/__init__.py
            - run: pytest tests/test_from_source.py -vvv 
    pytest_noinit_python3_s_from:
        executor:
            name: py3_s
        steps:
            - checkout
            - run: apt update; apt -y install curl python3-yaml
            - run: curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py; python get-pip.py
            - run: echo $PYTHONPATH
            - run: pip install -U pytest
            - run: rm -rf source/__init__.py
            - run: pytest tests/test_from_source.py -vvv 
   
              
    pytest_python2_direct:
        executor:
            name: py2
        steps:
            - checkout
            - run: apt update; apt -y install curl python-yaml
            - run: curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py; python get-pip.py
            - run: echo $PYTHONPATH
            - run: pip install -U pytest
            - run: pytest tests/test_direct_import.py -vvv 
    pytest_python2_s_direct:
        executor:
            name: py2_s
        steps:
            - checkout
            - run: apt update; apt -y install curl python-yaml
            - run: curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py; python get-pip.py
            - run: echo $PYTHONPATH
            - run: pip install -U pytest
            - run: pytest tests/test_direct_import.py -vvv 
    pytest_python3_direct:
        executor:
            name: py3
        steps:
            - checkout
            - run: apt update; apt -y install curl python3-yaml
            - run: curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py; python get-pip.py
            - run: echo $PYTHONPATH
            - run: pip install -U pytest
            - run: pytest tests/test_direct_import.py -vvv 
    pytest_python3_s_direct:
        executor:
            name: py3_s
        steps:
            - checkout
            - run: apt update; apt -y install curl python3-yaml
            - run: curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py; python get-pip.py
            - run: echo $PYTHONPATH
            - run: pip install -U pytest
            - run: pytest tests/test_direct_import.py -vvv 
    
    pytest_python2_from:
        executor:
            name: py2
        steps:
            - checkout
            - run: apt update; apt -y install curl python-yaml
            - run: curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py; python get-pip.py
            - run: echo $PYTHONPATH
            - run: pip install -U pytest
            - run: pytest tests/test_from_source.py -vvv 
    pytest_python2_s_from:
        executor:
            name: py2_s
        steps:
            - checkout
            - run: apt update; apt -y install curl python-yaml
            - run: curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py; python get-pip.py
            - run: echo $PYTHONPATH
            - run: pip install -U pytest
            - run: pytest tests/test_from_source.py -vvv 
    pytest_python3_from:
        executor:
            name: py3
        steps:
            - checkout
            - run: apt update; apt -y install curl python3-yaml
            - run: curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py; python get-pip.py
            - run: echo $PYTHONPATH
            - run: pip install -U pytest
            - run: pytest tests/test_from_source.py -vvv 
    pytest_python3_s_from:
        executor:
            name: py3_s
        steps:
            - checkout
            - run: apt update; apt -y install curl python3-yaml
            - run: curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py; python get-pip.py
            - run: echo $PYTHONPATH
            - run: pip install -U pytest
            - run: pytest tests/test_from_source.py -vvv 
                
workflows:
    build_and_test:
        jobs:
            - pytest_python2_direct
            - pytest_python3_direct
            - pytest_python2_s_direct
            - pytest_python3_s_direct
            - pytest_python2_from
            - pytest_python3_from
            - pytest_python2_s_from
            - pytest_python3_s_from
            - pytest_noinit_python2_direct
            - pytest_noinit_python3_direct
            - pytest_noinit_python2_s_direct
            - pytest_noinit_python3_s_direct
            - pytest_noinit_python2_from
            - pytest_noinit_python3_from
            - pytest_noinit_python2_s_from
            - pytest_noinit_python3_s_from
