version: 2.1

# Executors define environment where jobs will be run.
executors:
    snippets:
        docker:
            - image: cnerg/snippets
              auth:
                username: $DOCKERHUB_USER
                password: $DOCKERHUB_PASS

jobs:
    # CI initializing job.
    init:
        executor:
            name: snippets
        steps:
            - checkout
            - run: ls -la
            - run: pip install -U coverage coveralls PyYAML
            - run: coverage run --source=. -m pytest
            - run: coverage report
            - run: coverage html
            - run: coveralls
    ### Template. ###
    # test_script_x:
    #     executor:
    #         name: snippets
    #     steps:
    #         - checkout
    #         - run:
    #               name: Test script X.
    #               command: |
    #                   echo "This is a template job."

workflows:
    test:
        jobs:
            - init:
                context: dockerhub
    ### Template. ###
    #         - test_script_x:
    #             context: dockerhub
    #             requires:
    #                 - init
