version: 2.1


# Executors define environment where jobs will be run.
executors:
    snippets:
        docker:
            - image: pyne/pyne_ubuntu_16.04
        environment:
            #PYTHONPATH: ~/project/
            
jobs:
    pytest:
        executor:
            name: snippets
        steps:
            - checkout
            - run: 
                name: Run pytest
                command: pytest tests -vvv 
                
workflows:
    build_and_test:
        jobs:
            - pytest
