version: 2.1

# Executors define environment where jobs will be run.
executors:
    snippets:
        docker:
            - image: cnerg/snippets
              auth:
                username: $DOCKERHUB_USER
                password: $DOCKERHUB_PASS

jobs:
    # CI initializing job.
    init:
        executor:
            name: snippets
        steps:
            - checkout
            - run: ls -la
    test_t_test:
        executor:
            name: snippets
        steps:
            - checkout
            - run:
                  name: Test the t-test module.
                  command: |
                      pytest tests/test_twosample_ttest.py -vvv
    ### Template. ###
    # test_script_x:
    #     executor:
    #         name: snippets
    #     steps:
    #         - checkout
    #         - run:
    #               name: Test script X.
    #               command: |
    #                   echo "This is a template job."

workflows:
    test:
        jobs:
            - init:
                context: dockerhub
            - test_t_test:
                context: dockerhub
    ### Template. ###
    #         - test_script_x:
    #             context: dockerhub
    #             requires:
    #                 - init
