version: 2.1


# Executors define environment where jobs will be run.
executors:
    snippets:
        docker:
            - image: cnerg/snippets
        environment:
            #PYTHONPATH: ~/project/
            
jobs:
    # Template.
    # test_script_x:
    #     executor:
    #         name: snippets
    #     steps:
    #         - checkout
    #         - run: 
    #             name: Test script X.
    #             command: 
                
workflows:
    # Template.
    # test_scripts:
    #     jobs:
    #         - test_script_x
    #         - test_script_y:
    #             requires:
    #                 - test_script_x
