version: 2.1


# Executors define environment where jobs will be run.
executors:
    snippets:
        docker:
            - image: pyne/pyne_ubuntu_16.04
        environment:
            PYTHONPATH: ~/project/source/
            
jobs:
    pytest:
        executor:
            name: snippets
        steps:
            - checkout
            - run: apt update; apt -y install curl python-yaml
            - run: curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py; python get-pip.py
            - run: pip install -U pytest
            - run: 
                name: Run pytest
                command: pytest tests -vvv 
                
workflows:
    build_and_test:
        jobs:
            - pytest
